### ISSUE TITLE
DrawVisibleBounds

### ISSUE THREAD

**Issue by creold** [joshbduncan/illustrator-scripts#7]
Hi @joshbduncan ,

I haven't seen a bug in `getVisibleBounds()` in a long time. In the FOR loop that finds the mask in the clipping group (119 line). 
```
} else {
          clippedItem = curItem;
          break;
        }
```
This ELSE will break the FOR loop on the first element, and there may be cases where the mask is moved in the hierarchy and then the function returns the dimensions of the top object instead of the mask =).
![maskPath](https://github.com/joshbduncan/illustrator-scripts/assets/32217031/98d3c869-1a9b-41b2-89a8-b165b690e09b)

**Comment by joshbduncan** [comment]
Hmm, I never really thought about someone moving the clipping path in the layer stack. I'll dig into this when I have time and try to sort out a solution. Thanks for letting me know!

**Comment by creold** [comment]
For example, https://github.com/nimbling/Nimbling_Scripts#clip-scripts scripts, when drawing with a script, the bottom object is assigned a mask and remains the bottom object in the stack.That is, cases where the mask is not only at the top of the group are real :)

**Comment by joshbduncan** [comment]
So, I think that piece of code was actually a relic from an early version of the script. Seems that if the script actually makes it to that part then something funky is going on and in that case, I'll just return the visible bounds.

**Comment by joshbduncan** [comment]
So, it turns out that the last else statement was needed. For example, if a clipped group was then grouped again, the script were produce incorrect results. I added a catch to see if the `clippedItem` is undefined after iterating over all of a clipped group pageItems, and if so, the function just sets the clipped item into the original `curItem`.

**Comment by creold** [comment]
I changed the function code in a similar way on Sunday when I needed to get bounds in a script. It's an acceptable solution if we don't find any more complicated cases =)

**Comment by joshbduncan** [comment]
Oh, I'm sure there are plenty more cases that would break this script. There are so many junk files out there, especially ones exported to .ai and .pdf from other software. I'll close this for now. Thanks again for your help!

**Comment by joshbduncan** [comment]
So, I found something interesting... If you move the from the first position in the layer stack like pic above, then save and reopen the file, Ai actually moves it back to the correct spot. The clipping isn't moved to you actually close the file, so it seems that Ai does some cleanup when opening files (tested with both .ai and .pdf).

**Comment by creold** [comment]
Wow. I didn't know about this because I don't use masks much in my work. And a friend said he knew about this feature in Illustrator. In any case, the recursive function makes sense, because the user can create a group in the document with the mask moved and run the script when the mask is not yet on top :)

**Comment by joshbduncan** [comment]
Yes, your bug issue definitely needed to be fixed. I could see many situations where a file being worked on had unordered clipping mask layers. I was just surprised to see Ai actually changing a file during the open process and wanted to share it. Thanks again!
